# Generated by Django 2.2 on 2020-02-01 09:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('projectapp', '0005_stdclassrouting'),
    ]

    operations = [
        migrations.CreateModel(
            name='stdresult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result_point', models.CharField(max_length=30)),
                ('grate', models.CharField(max_length=30)),
                ('stdsubjectentry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stdresult', to='projectapp.Stdsubjectentry')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stdresult', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
