# Generated by Django 2.2 on 2020-02-01 09:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('projectapp', '0006_stdresult'),
    ]

    operations = [
        migrations.CreateModel(
            name='stdaccountingsite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('selary_month', models.CharField(max_length=30)),
                ('monthof_amount', models.CharField(max_length=30)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stdaccountingsite', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
