# Generated by Django 2.2 on 2020-02-01 10:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('projectapp', '0007_stdaccountingsite'),
    ]

    operations = [
        migrations.CreateModel(
            name='Logintype',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_type', models.CharField(choices=[('teacher', 'teacher'), ('Student', 'Student')], default='Student', max_length=30)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Logintype', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
