# Generated by Django 2.2 on 2020-02-01 10:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projectapp', '0009_auto_20200201_1013'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logintype',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='Logintypee', to=settings.AUTH_USER_MODEL),
        ),
    ]
