# Generated by Django 2.2 on 2020-02-01 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectapp', '0011_auto_20200201_1127'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stdnotice',
            name='description_notice',
            field=models.CharField(max_length=3000),
        ),
    ]
