# Generated by Django 2.2 on 2020-02-01 16:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projectapp', '0015_auto_20200201_1354'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stdsubjectlist',
            old_name='subjectcode',
            new_name='subject_code',
        ),
    ]
