# Generated by Django 2.2 on 2020-02-02 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectapp', '0017_auto_20200202_0447'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stdaccountingsite',
            name='selary_month',
            field=models.CharField(choices=[('January', 'January'), ('Fabruary', 'Fabruary')], default='January', max_length=30),
        ),
    ]
