# Generated by Django 2.2 on 2020-02-02 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectapp', '0018_auto_20200202_0829'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stdaccountingsite',
            name='selary_month',
            field=models.CharField(choices=[('January', 'January'), ('February', 'February'), ('March', 'March'), ('April', 'April'), ('May', 'May'), ('June', 'June'), ('July', 'July'), ('August', 'August'), ('September', 'September'), ('October', 'October'), ('November', 'November'), ('December', 'December')], default='January', max_length=30),
        ),
    ]
